#pragma once

//based on VR....

#define VR_KEY_SPACE              32
#define VR_KEY_APOSTROPHE         39  
#define VR_KEY_COMMA              44  
#define VR_KEY_MINUS              45  
#define VR_KEY_PERIOD             46  
#define VR_KEY_SLASH              47  
#define VR_KEY_0                  48
#define VR_KEY_1                  49
#define VR_KEY_2                  50
#define VR_KEY_3                  51
#define VR_KEY_4                  52
#define VR_KEY_5                  53
#define VR_KEY_6                  54
#define VR_KEY_7                  55
#define VR_KEY_8                  56
#define VR_KEY_9                  57
#define VR_KEY_SEMICOLON          59  
#define VR_KEY_EQUAL              61  
#define VR_KEY_A                  65
#define VR_KEY_B                  66
#define VR_KEY_C                  67
#define VR_KEY_D                  68
#define VR_KEY_E                  69
#define VR_KEY_F                  70
#define VR_KEY_G                  71
#define VR_KEY_H                  72
#define VR_KEY_I                  73
#define VR_KEY_J                  74
#define VR_KEY_K                  75
#define VR_KEY_L                  76
#define VR_KEY_M                  77
#define VR_KEY_N                  78
#define VR_KEY_O                  79
#define VR_KEY_P                  80
#define VR_KEY_Q                  81
#define VR_KEY_R                  82
#define VR_KEY_S                  83
#define VR_KEY_T                  84
#define VR_KEY_U                  85
#define VR_KEY_V                  86
#define VR_KEY_W                  87
#define VR_KEY_X                  88
#define VR_KEY_Y                  89
#define VR_KEY_Z                  90
#define VR_KEY_LEFT_BRACKET       91  
#define VR_KEY_BACKSLASH          92  
#define VR_KEY_RIGHT_BRACKET      93  
#define VR_KEY_GRAVE_ACCENT       96  
#define VR_KEY_WORLD_1            161 
#define VR_KEY_WORLD_2            162 

/* Function keys */
#define VR_KEY_ESCAPE             256
#define VR_KEY_ENTER              257
#define VR_KEY_TAB                258
#define VR_KEY_BACKSPACE          259
#define VR_KEY_INSERT             260
#define VR_KEY_DELETE             261
#define VR_KEY_RIGHT              262
#define VR_KEY_LEFT               263
#define VR_KEY_DOWN               264
#define VR_KEY_UP                 265
#define VR_KEY_PAGE_UP            266
#define VR_KEY_PAGE_DOWN          267
#define VR_KEY_HOME               268
#define VR_KEY_END                269
#define VR_KEY_CAPS_LOCK          280
#define VR_KEY_SCROLL_LOCK        281
#define VR_KEY_NUM_LOCK           282
#define VR_KEY_PRINT_SCREEN       283
#define VR_KEY_PAUSE              284
#define VR_KEY_F1                 290
#define VR_KEY_F2                 291
#define VR_KEY_F3                 292
#define VR_KEY_F4                 293
#define VR_KEY_F5                 294
#define VR_KEY_F6                 295
#define VR_KEY_F7                 296
#define VR_KEY_F8                 297
#define VR_KEY_F9                 298
#define VR_KEY_F10                299
#define VR_KEY_F11                300
#define VR_KEY_F12                301
#define VR_KEY_F13                302
#define VR_KEY_F14                303
#define VR_KEY_F15                304
#define VR_KEY_F16                305
#define VR_KEY_F17                306
#define VR_KEY_F18                307
#define VR_KEY_F19                308
#define VR_KEY_F20                309
#define VR_KEY_F21                310
#define VR_KEY_F22                311
#define VR_KEY_F23                312
#define VR_KEY_F24                313
#define VR_KEY_F25                314
#define VR_KEY_KP_0               320
#define VR_KEY_KP_1               321
#define VR_KEY_KP_2               322
#define VR_KEY_KP_3               323
#define VR_KEY_KP_4               324
#define VR_KEY_KP_5               325
#define VR_KEY_KP_6               326
#define VR_KEY_KP_7               327
#define VR_KEY_KP_8               328
#define VR_KEY_KP_9               329
#define VR_KEY_KP_DECIMAL         330
#define VR_KEY_KP_DIVIDE          331
#define VR_KEY_KP_MULTIPLY        332
#define VR_KEY_KP_SUBTRACT        333
#define VR_KEY_KP_ADD             334
#define VR_KEY_KP_ENTER           335
#define VR_KEY_KP_EQUAL           336
#define VR_KEY_LEFT_SHIFT         340
#define VR_KEY_LEFT_CONTROL       341
#define VR_KEY_LEFT_ALT           342
#define VR_KEY_LEFT_WINDOWS       343
#define VR_KEY_RIGHT_SHIFT        344
#define VR_KEY_RIGHT_CONTROL      345
#define VR_KEY_RIGHT_ALT          346
#define VR_KEY_RIGHT_WINDOWS      347
#define VR_KEY_MENU               348

